### ISSUE TITLE
Some sources do not handle aborts without a callback

### ISSUE THREAD

**Issue by elavoie** [pull-stream/pull-stream#101]
The following sources do not correctly handle aborting without providing a callback:
* values()
* empty()
* error()
* keys()
* once()

which is correctly handled by these sources:
* count()
* infinite()

**Comment by dominictarr** [comment]
I think it's now count and infinite which should be considered _wrong_. If you look at it as a majority vote from the entire pull-stream ecosystem there are probably most that assume a callback. It's simpler to make a callback necessary, since there isn't really ever a good reason to not have one, and then implementers don't have to have abort tests (which are a pain as they are) with and without callbacks.

**Comment by elavoie** [comment]
@dominictarr Ok... That should simplify my paper also. I had many corner cases to think about because of that. What was the initial motivation for aborting without a callback?

That does not completely solve the issue though, we need to enforce having sinks and through never abort *without* a callback now. But can I assume this is the direction we are going and progressively make sure all community contributed modules also follow those guidelines?

I am embedding the protocol invariants in http://github.com/elavoie/pull-stream-protocol-checker and http://github.com/elavoie/pull-stream-reference-modules, and applying them for systematic testing of modules compliance with the pull-stream protocol (https://github.com/elavoie/ecoop18-pull-stream-experiments/blob/master/test/index.js) by testing all cases automatically.

**Comment by dominictarr** [comment]
I can't remember now, it probably just seemed easy at the time.

I don't really know if community modules have all the behaviour correct, and handling abort is the hardest part. I havn't conducted a review of the internal patterns used it community modules... There isn't really a way to _enforce_ anything except fix them or post issues when you find something. Okay you could ceck if they have a test case for abort.

**Comment by dominictarr** [comment]
I a pull-stream module happens to work when you don't supply the callback, consider that "undefined behaviour". You are outside of the spec, anything could happen, please keep your hands inside the vehicle.

**Comment by elavoie** [comment]
@dominictarr It seems to me avoiding the callback makes the sink implementation a little cleaner because an empty function does not need to be supplied when the answer is irrelevant. However, it requires *all* sources to support that behaviour, which seems quite a constraint on community implementers and painful to enforce.

I have the infrastructure to test for compliance automatically as mentioned before, that is what I used to find issue #104. If we maintain a list of the most popular modules, I can make sure that at least those follow the pull-stream callback protocol and are interoperable. For the modules I am not personally supporting, authors will be able to use the modules to write their own tests. 

I am putting the final touches on a paper that provides a formalization of the pull-stream design pattern:

A formalization for Specifying and Implementing Correct Pull-Stream Modules
https://www.overleaf.com/read/mmqffvhmwrpd

I will submit to ECOOP18 by the end of the week. It can also serve as a reference for implementers.

I am closing the issue as the paper and my tests assume all requests have an answer callback now.
