### ISSUE TITLE
Code example for through streams in README is wrong.

### ISSUE THREAD

**Issue by harrysarson** [pull-stream/pull-stream#107]
Hi, I was looking at the README and I can't understand the given example of the through stream. I was wondering if this example could be clarified for me.

In the  README:

> ### Through
>
>  
>  A through stream is a reader on one end and a readable on the other.
>  It's Sink that returns a Source.
>  That is, it's just a function that takes a `read` function,
>  and returns another `read` function.
>  
>  ```js
>  function map (read, map) {
>    //return a readable function!
>    return function (end, cb) {
>      read(end, function (end, data) {
>        cb(end, data != null ? map(data) : null)
>      })
>    }
>  }
> ```

Here it states that through is
> just a function that takes a `read` function,

However, in the code example `map` is a function that takes a read function and also a `map` function.

Adding an example showing how this map function could be used may help to clarify this.

Many thanks, Harry :)

**Comment by jamen** [comment]
This could be an error, I noticed this too but never raised it. Someone correct me if I'm wrong.  

Looking at [`pull.map`](https://github.com/pull-stream/pull-stream/blob/master/throughs/map.js) you're supposed to use a 3rd function to implement the `mapper` param.  As far as I'm aware, sinks are [not allowed](https://github.com/pull-stream/pull-stream/blob/f36f573a08e0cea7121c24a9b3466616a0f94484/pull.js#L5) to have two parameters.  

I agree with adding an example here.

**Comment by harrysarson** [comment]
Yeah, I will make a PR to correct this.
