### ISSUE TITLE
Support asynchronous iterator (Node 10)

### ISSUE THREAD

**Issue by staltz** [pull-stream/pull-stream#112]
[async iterators](http://exploringjs.com/es2018-es2019/ch_asynchronous-iteration.html), now supported in Node 10 and some browsers, allows us to use the `for-await-of` syntax, e.g.:

```js
async function main() {
  var ps = pull(
    pull.count(),
    pull.take(21),
    pull.asyncMap((data, cb) => {
      setTimeout(() => { cb(null, data + 1) }, 300)
    })
  )

  for await (const x of ps) {
    console.log(x)
  }
}
```

I can submit a pull request for this, as I already have a working implementation locally.

That said, since pull streams can be any (hand-written) function that complies to the pull-stream spec, another option is to create a helper `awaitable`:

```js
for await(const x of awaitable(ps)) {
  console.log(x)
}
```

**Comment by staltz** [comment]
Implementation of `awaitable.js` in case people want to play with it:

```js
module.exports = function awaitable(readable) {
  return {
    [Symbol.asyncIterator]() {
      return {
        next() {
          return new Promise(function (resolve, reject) {
            readable(null, function (errOrEnd, data) {
              if (errOrEnd === true) {
                return resolve({done: true});
              } else if (errOrEnd) {
                return reject(errOrEnd);
	      } else {
                return resolve({done: false, value: data});
              }
            });
          });
        }
      }
    }
  }
}
```

**Comment by dominictarr** [comment]
I'm not a fan of await, I'd rather not add that as a feature for that to pull-stream, but you of course you could publish awaitable as a module.

but in particular there needs to be a way to abort the stream, and I don't really see the advantage of `for in` (with a try-catch around it) when you could just do `pull.drain`

**Comment by staltz** [comment]
It is indeed like a drain, which also doesn't have a way of aborting.

Besides the syntactic aspect of this, it also helps with interoperability because you could concatenate two async iterables without having to know what's the true nature of the primitive behind the async iterator interface. For instance concatenate a pull stream with a Node.js stream, transparently.

I know you're not a fan of these new Promise-bases features, but what's the basis for our decisions with this library?

**Comment by ahdinosaur** [comment]
ooh nice, :+1: an `awaitable` helper published as a separate module (a la [`pull-iterable`](https://github.com/nrkn/pull-iterable)).

**Comment by dominictarr** [comment]
@staltz 
> but what's the basis for our decisions with this library?
the core pull-stream library hasn't had a feature addition in a very long time. just perf fixes (because there hasn't been a bug in ages).

Generally I encourage people to publish a module, and there is a doc site with a list of all module. grab-bag modules like pull-stream are useful for starting an ecosystem, but they become bloated or bikeshedariums, so my policy is to refactor everything out into modules, and focus on stability and perf.
