### ISSUE TITLE
Possible to have async transform w/ multiple results?

### ISSUE THREAD

**Issue by loveencounterflow** [pull-stream/pull-stream#118]
I'm trying to find out whether and how it would be possible to have a transform `t` such that in

    pull( source, t, sink )

the following are satisfied:

* `t` retrieves, in an asynchronous fashion, any number of pieces of data `r` for each piece of data `d` coming down from `source`;
* `t` passes each `r` into the pipeline, e.g. by calling a function;
* each `r` should be delivered to downstream ASAP and not be buffered;
* when `t` is done, it should probably be required to somehow signal that, e.g. by calling another function.

I know I can build something like the above by using `async_map`, but since that function works with a callback that expects to be called exactly once, I have to build an intermediate array of results first, wait for it to arrive from the asynchronous step, and then unpack the array. It is this intermediate buffering that I'm trying to avoid, but don't know how to.

**Comment by loveencounterflow** [comment]
I'm struggling to provide a working minimal example, but I will say that my use case is building a text transformation that reads lines and processes them into chunks of text with markup added. Since there may be several pieces of markup in one line, a single input may produce any number of output chunks. No problem here as long as the processing is synchronous. 

But I also want to e.g. make calls to a database that are triggered by markup in the source; again, this may produce zero or more results to send down the line. Since the output may be arbitrarily long—think hundreds of printed pages worth—it would be great to send all chunks on as soon as they arrive. 

> use paramap and cb an array, or map and return a stream - then pipe through pull.flatten()
I think `paramap` doesn't meet my use case

**Comment by dominictarr** [comment]
okay! that was quite helpful to know. In particular: if this is processing some sort of (xml?) input, you certainly want the output transforms to be in the same order, for the corresponding input.

Since each output can be a maybe massive data, it should be a stream.
`pull(pull.map(function (d) { return createStream(d) }), pull.flatten())`

where createStream is your thing that goes and gets the output stream.

**Comment by loveencounterflow** [comment]
Ah ok, that's a cool idea to go and try.
