### ISSUE TITLE
a question about drain.js

### ISSUE THREAD

**Issue by huahang** [pull-stream/pull-stream#128]
I am learning `pull-stream`. And I have a question about drain.js.

In this line:
https://github.com/pull-stream/pull-stream/blob/master/sinks/drain.js#L24
`else if(op && false === op(data) || abort) {`

Is the `|| abort` part redandent?

Because if `abort` is true, then it should execute into the previous branch:
https://github.com/pull-stream/pull-stream/blob/master/sinks/drain.js#L18

**Comment by regular** [comment]
yes, I think you are right about this.

**Comment by huahang** [comment]
Is it valid to call `sink.abort()` in `drain.js`'s `function op() {}`?

**Comment by huahang** [comment]
Is it valid to call `sink.abort()` in `drain.js`'s `function op() {}`?

**Comment by dominictarr** [comment]
it would be better to return false if possible. `drain.abort()` is a feature that seemed necessary when I first created it, but now I'm not sure if I ever used it. (maybe in muxrpc?)

**Comment by dominictarr** [comment]
actually, calling abort within the op function might cause the abort call `read(true, cb)` to run twice. once inside abort() and also in the if block. but as I said better to return false. would be curious if any public pull stream code uses `drain.abort()`

**Comment by regular** [comment]
@dominictarr I am using `drain.abort()` extensively in UI code. The scenario is updating an UI element from a live stream and aborting when the element is removed from the DOM (using a mutant hook function).

**Comment by huahang** [comment]
I see. this is my concern indeed. i'll try to avoid calling `abort()` from `function op()`. 
Thank you Dominic~

> actually, calling abort within the op function might cause the abort call `read(true, cb)` to run twice. once inside abort() and also in the if block. but as I said better to return false. would be curious if any public pull stream code uses `drain.abort()`
