### ISSUE TITLE
Binary Streams

### ISSUE THREAD

**Issue by skeggse** [pull-stream/pull-stream#15]
I don't know how this could fit into pull-stream, but it would be nice to reduce overhead. It seems like it's relevant, because pull streams are nice when reading from a resource, and simplify the process of consuming from the stream.

#### Producing Binary

Let's say I have a through stream that is written to reach a socket. Let's say that for every object I read, I need to write a header to the socket. I don't want to interact directly with the socket, but instead use the existing mechanism to transfer the header. I could create a buffer that contains both the header and the encoded object, but that involves a copy which is often expensive. Ideally, I could just call `cb` twice--once with the header and once with the data.

```js
function header(data) {
  // creates a header for the data
  // returns a string or buffer
}

function encode(data) {
  // encodes the data (could just be JSON.stringify)
  // returns a string or buffer
}

pull.Through(function(read) {
  return function(end, cb) {
    read(end, function(end, data) {
      if (end)
        return cb(end);
      cb(null, header(data));
      cb(null, encode(data));
    });
  };
});
```

I can't just call the callback twice, though, because the callback can be used to signal state to the consuming stream:

```js
pull.Through(function(read) {
  return function(end, cb) {
    var header;
    // read gets different callbacks that dictate the state of
    // the through stream
    read(end, head);

    function head(end, data) {
      if (end)
        return cb(end);
      // consume header data, put into header variable
      read(null, body);
    }

    function body(end, data) {
      if (end)
        return cb(end);
      // consume body
      cb(null, decode(data, header));
    }
  };
});
```

#### Consuming Binary

When writing a parser using these streams, it's nice to request a specific number of bytes, kinda like `read(size)` from node's streams. I worked around this, but it will probably break some things because it changes the read function's signature from `read(end, cb)` to `read(end, bytes, cb)`. I suppose it could be `read(end, cb, bytes)`, but that would make the `bytes` parameter advisory, which somewhat defeats the purpose, and would break the convention of having the callback be the last parameter.

```js
// consumes buffers, produces specified-size buffers
pull.Through(function(read) {
  // maintain excess bytes
  var buffer = [], bufferLength = 0;
  return function(end, bytes, cb) {
    // push the data into the buffer
    function push(data, start) {
      start || (start = 0);
      bufferLength += data.length - start;
      buffer.push(start ? data.slice(start) : data);
    }

    // merge and empty the buffer
    function merge() {
      var sum = Buffer.concat(buffer, bufferLength);
      buffer.length = bufferLength = 0;
      return sum;
    }

    // pluck size bytes from the beginning of the buffer
    function pluck(size) {
      var sum = merge();
      if (sum.length === size)
        return sum;
      push(sum, size);
      return sum.slice(0, bytes);
    }

    // callback with the requested bytes of data, buffer the rest
    function done(data) {
      if (data.length === bytes)
        return cb(null, data);
      push(data, bytes);
      cb(null, data.slice(0, bytes));
    }

    read(end, function more(end, data) {
      if (end) {
        // if (end === true)
        //   return cb(new Error('excess data still in buffers'));
        return cb(end);
      }
      if (bufferLength === 0 && data.length >= bytes)
        return done(data);
      push(data);
      // if still not enough data, read more
      if (bufferLength < bytes)
        return read(null, more);
      // enough data, pluck from buffer
      cb(null, pluck(bytes));
    });
  };
});
```

#### Other Thoughts

My real pain point right now is the ability to produce multiple pieces of data for one read operation. The problem is that, of course, a read operation is designed to get one piece of data.

**Comment by regular** [comment]
Is there a reason why this is still open? This use case is solved by https://github.com/dignifiedquire/pull-length-prefixed/blob/master/src/decode.js, right?

**Comment by dominictarr** [comment]
oh, there are actually quite a few modules for working with binary now.
basically the answer is use https://github.com/dominictarr/pull-reader gives you what @skeggse was asking for, but without adding that functionality to pull-streams core
