### ISSUE TITLE
throw out the junk

### ISSUE THREAD

**Issue by dominictarr** [pull-stream/pull-stream#22]
i wrote this module very early when doing the pull-stream thing.
some of the functions should be removed because they are rarely used,
or are two specialized.

depthFist, widthFirst, leafFirst have been moved to their own module,
and highWatermark could go too. probably a bunch of stuff. maybe one or two could be added?

probably could grep all my code and find how often I have used all of these.

**Comment by TehShrike** [comment]
Aw, is there no more junk to clean out?  I was thinking of going through to do some pruning to try to be useful :-)

**Comment by dominictarr** [comment]
aha, I think it's mostly okay. it's definitely much lighter and it's refactored so you can reference just the stuff you need (for browserify bundles)

**Comment by dominictarr** [comment]
feel free to have a look though. really it's about filtering out patterns that arn't used in practice.
one thing might be `take` it could be much simpler if it only took an number (not a function) and I _think_ that might be how it's mostly used.
