### ISSUE TITLE
handle error/destruction/close of destination

### ISSUE THREAD

**Issue by dominictarr** [pull-stream/pull-stream#3]
@raynos so I think I figured out what to do here.

If the reader/sink end decides to end early, (maybe due to error, or close, or just because)
the propagate the end message to the source by calling `read(end)`, where end is truthy.

a through needs to handle it like this, by default.
``` js
pull.Through(function (read) {
  return function (end, cb) {
    if(end) {
      //drop what you are doing, etc
      //propagate the message, and pass the response straight
      return read(end, cb)
    }
    //everything is okay, do your stuff
    read(null, function (end, data) {
      cb(end, data)
    })
  }
})
```

So, if a readable receives and preemptive `end`, it should just pass that through to the source, and probably not bother interfering with the result. Just drop what you'r doing
and tell the source.

That should be the case for the vast majority of duplex streams.

**Comment by dignifiedquire** [comment]
@dominictarr does this issue still need to be open?

**Comment by dominictarr** [comment]
haha, no this is very solved now
