### ISSUE TITLE
Include flatmap stream?

### ISSUE THREAD

**Issue by phated** [pull-stream/pull-stream#59]
I was reading http://dominictarr.com/post/149248845122/pull-streams-pull-streams-are-a-very-simple and a `flatmap` stream was mentioned at the end.  I assumed it was part of pull-stream so I tried to use it and then noticed it wasn't a method.  It would be simple to copy-paste into a project but it seems like a useful utility method that could be part of the core library.  Is there a reason it isn't included?

**Comment by ahdinosaur** [comment]
hey @phated,

[`flatMap` used to be a core method in `2.x`](https://github.com/pull-stream/pull-stream/blob/598f108149695114704469267354bf02c4d85cfc/throughs.js#L325-L347), but then was taken out of core in `3`. @dominictarr might be able to share more about this story.

i agree it's a useful utility, if it's actually not a module anywhere anymore then i recommend re-publishing it as a `pull-flatmap` module (which we can add to the website and if you want, move to be within this org), we would rather not include anything more in this core module. :smiley:

**Comment by phated** [comment]
I can understand the desire to not pollute the core module.  I'm just getting into pull-streams and don't want to take on more OSS burden than I am under so I likely won't create this as a module.

**Comment by dignifiedquire** [comment]
Also, "secret" trick, I keep just using `pull.map(), pull.flatten()` in combination for the same effect, and actually like it, as it is quite explicit in what is happening.

**Comment by phated** [comment]
It seems the commit that removed it was https://github.com/pull-stream/pull-stream/commit/c8c1db28a6449a384bc19c963fa13ca25fd86dea but it might have been a mistake due to being interwoven with `highWaterMark` and other "clever" methods.

**Comment by dominictarr** [comment]
@phated yeah, you can use map with flatten, and you can also use https://github.com/pull-stream/pull-through to similar effect. pull-streams are so simple and focused once they are correct they are _done_ and you'll probably get very few issues posted on them.

I'll publish the flatmap example for you though!

**Comment by dominictarr** [comment]
https://www.npmjs.com/package/pull-flatmap
