### ISSUE TITLE
a is function and has length?

### ISSUE THREAD

**Issue by jamen** [pull-stream/pull-stream#70]
I was looking at this line in `./pull.js`:

```js
if (typeof a === 'function' && a.length === 1) {
```

I was wondering how this could ever be true?  unless someone sets `.length = 1` on a function somewhere

**Comment by TehShrike** [comment]
The line in question: https://github.com/pull-stream/pull-stream/blob/8c0347d8e7f88171cd4c45eec22b42c5c7332fac/pull.js#L5

**Comment by TehShrike** [comment]
@jamen [`Function.length`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) returns the number of arguments expected by the function.

I don't see it used very often.

**Comment by jamen** [comment]
Ohh, I see.  Thanks.  :^)
