### ISSUE TITLE
flatten

### ISSUE THREAD

**Issue by nichoth** [pull-stream/pull-stream#75]
What is the expected behavior for flattening a stream of async streams? Do you drain each before moving to the next (like cat), or do you expect the flattened stream to emit events in the order they are returned from the sources (like pull-many)? 

----------

For the long story, this came up because I have a stream of streams, and each nested stream emits several events before ending. We want to emit all those events on a single streams (flatten them), but emit them in the order they are received. It looks like flatten drains each in sequence. 

For an even higher level view, I have a set of strings. Each string maps to an asynchronous function. When you call the async function, we want to emit at least 2 events, one when the function is called, and another when the function has resolved. This allows us to model the state of the function call over time. You can map the functions to streams, which is where the nested streams come from. Imagine someone clicking several buttons at random times, each of which starts an http request.

I would be curious if anyone has ideas about this pattern or something better.

--------------

(thinking out loud about this)

requirements
* Infinite async function calls can be done in parallel
* responses are emitted in the order they are received
* each event in the source maps to several events emitted by the transform (or a new stream)
* backpressure… this is probably irrelevant for the use case

Can use something like pushable to queue up many events from one source event. What would that operator be called?
Can create a merge stream (pull-many) where you can dynamically add more streams to it. Then wrap that in a transform (flat merge) stream.

I think this algorithm is `flatMap` in rxjs.

**Comment by nichoth** [comment]
It looks like pull-many has a `add` method that I can use to solve this.

**Comment by dominictarr** [comment]
yeah, sounds like you want pull-many.
you should use `m.cap()` inside the end handler, that will make the merged stream end after all the input streams have
