### ISSUE TITLE
Should a source stream expect to be called without a callback?

### ISSUE THREAD

**Issue by tjconcept** [pull-stream/pull-stream#76]
I was just wondering... Comparing this code:

https://github.com/pull-stream/pull-stream/blob/master/sources/values.js#L7
https://github.com/pull-stream/pull-stream/blob/master/sources/infinite.js#L5
https://github.com/pull-stream/pull-stream/blob/master/util/abort-cb.js

"values" and "infinite" both produce source streams, right? Why does only one of them check for the existence of `cb` (the "abort-cb" utility does not)?

My intuitive guess is that you need to check for existence, because you would like to allow someone doing `cb(true)` to abort mission.

**Comment by dominictarr** [comment]
yeah, in this case it means you can do `read(true)` and abort the stream. However, that ought to be considered _undefined behaviour_, and there are other streams where it will just try to call `cb` and if it is not a function, then it will throw.

**Comment by tjconcept** [comment]
Thanks, makes sense. Is it an inconsistency in this library then? I think I'd prefer to have the check to avoid coming up with noops when aborting from a sink.

**Comment by dominictarr** [comment]
I'd far sooner make not passing the callback an error, rather than making an optional callback a standard. Handling errors are the hardest part about writing a pull-stream, and so testing abort with callback, and also without callback doesn't seem like the best use of time.

**Comment by tjconcept** [comment]
Fair point about testing. Thanks.
