### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by nichoth** [pull-stream/pull-stream#85]
Is there an existing module that you use to handle errors? Say you want to do a callback if there is an error, then end the stream normally. Thanks everyone.

**Comment by dominictarr** [comment]
can you go into more detail here? there are lots of way "there is an error" can be true. do you mean something throws? generally, each pull-stream should pass it's errors along, and then that is probably handled at the sink's callback.

**Comment by nichoth** [comment]
Thanks @dominictarr. I was thinking we have a source that ends with an error `cb(new Error())`, and when that happens we end the stream normally `cb(true)`. For example, if we are using pull-many, we have `pullMany([streams])`, and if one of the source streams errors, we don't want to abort all the others, so the stream with an error should end normally instead.

```js
function onErr (onErrorCb) {
    return function sink (read) {
        return function source (abort, cb) {
            read(abort, function onNext (end, data) {
                if (end && end !== true) {
                    onErrorCb(end)
                    return cb(true)
                }
                cb(end, data)
            }
        }
    }
}
```

**Comment by dominictarr** [comment]
looks good, now publish it

**Comment by nichoth** [comment]
https://www.npmjs.com/package/pull-catch

**Comment by dominictarr** [comment]
👍
