### ISSUE TITLE
Detecting end of stream

### ISSUE THREAD

**Issue by jamen** [pull-stream/pull-stream#87]
So if I'm making a module that takes a full pipeline (source to sink) and runs it, is there a standard/effective way to detect when it is done?

I know that sink modules usually provide a callback like `onEnd`, but this is not really consistent, nor controllable on the level I'm working with the streams (as the callback is already set and done by the time I'm running them).

I think one option would be to inject a through stream before the sink, and check for the end param, but I'm not sure if this is the best way or if a better way is wanted & could be made?

**Comment by nichoth** [comment]
I think you would need to take a non-standard stream, with a method like `onEnd`, that would be provided by a through stream in the pipeline. I'm curious, though, if you are taking a stream that is already fully connected, how are you using it? I wouldn't think there is any way to observe or interact with it once it is drained.

**Comment by jamen** [comment]
Like this:

```js
myModule(options, [ ...streams ])
```

When it receives that array it wouldn't be executed right away. 

But, when I do execute it with `pull()`, I was curious if there was a good standardized way to detect when it ends out of the box...  Because the module shouldn't care what the streams are, they are user defined and could be anything.

**Comment by nichoth** [comment]
Oh, ok — so you are getting an array of streams, then calling them yourself. In that case it should be easy to add a through stream anywhere in the pipeline that would call a function on end. Not sure if that exists as a module yet.

**Comment by jamen** [comment]
I was thinking it would be nice if it was out-of-the box.  I've been in a few situations now where I've wanted to know when a stream ends with `pull()`.  Sounds like general usecase.  What do you think?

**Comment by dominictarr** [comment]
@jamen can you describe your application? or applications that need this feature? I want know a concrete use-case.

**Comment by dignifiedquire** [comment]
I was needing this a couple of times so I wrote this thing: https://github.com/libp2p/js-libp2p-multiplex/blob/pull-stream/src/pull-end.js (need to pull it into its own module) which allows you to simply get called once the end has been reached. See the tests here for how you can use it: https://github.com/libp2p/js-libp2p-multiplex/blob/pull-stream/test/pull-end.spec.js

**Comment by dominictarr** [comment]
@dignifiedquire the problem with that is it includes some assumptions about what the sink is. for example, if the sink is a `pull-file-write` then whatever `onEnd` returns would be at the end of the file... that may or may not be what you want.

**Comment by jamen** [comment]
@dominictarr I've tried to create my project really fast to demonstrate what I mean, see [pull-task](https://github.com/jamen/pull-task#usage)

The reason it is needed here is because tasks can have dependency tasks.  When one of them is run, I need to know when it's dependency pipelines are finished before I start it.

I tried implementing my idea in the original post (injecting a through stream), but even that ended up being problematic for the last sink stream in the pipeline (the completion callback will execute before it, because its the second stream).

It would also be useful for logging completion.  But I feel like there is quite a few cases where it is helpful to detect when a pipeline is finished, I just can't think of specific scenarios right now.

**Comment by jamen** [comment]
Hmm, I'm trying to explain what I need in a good way.  

If there was some standard part of sink streams that let me know when they end, that would solve this.

**Comment by jamen** [comment]
I was thinking of this hypothetical usage for `pull` that would solve the problem:

```js
pull([ ...streams ], function finish () { ... })
```

But I understand that deviates a bit and would probably clutter to add it in.

**Comment by dominictarr** [comment]
@jamen no I mean what real world problem are you trying to solve?
I don't trust abstract requirements if you can't describe a practical tool that needs that.
It looks like you are building a gulp but will pull-streams.

what can you say about the types of sinks you need?

**Comment by jamen** [comment]
@dominictarr  I'm making `pull-vinyl` and `pull-task` so I can use them together like gulp.  Eventually I will create other modules like `pull-pug`, `pull-sass`, etc. (I have plan for them in my head right now)

But, I don't want them to be limited to what I want to use them for, that's probably why it seems abstract.  

Setting up a task for any pipeline you want would be nice, and reading/writing vinyls on their own would be nice too.  I want people to be able to use `pull-vinyl` or `pull-task` as they please.  I will probably use them for other things in the future as well.

The only setback is this issue in `pull-task`.

The types of sinks I need are made in `pull-vinyl` already, but I don't want `pull-task` to have to cater to specific sinks in order to know how to end.  Too me It feels like `pull-stream` should just have just have a mechanism for knowing when everything is finished, and that would solve this.

**Comment by dominictarr** [comment]
@jamen you are not answering my question. I need a concret description of what happens (I've never used gulp btw) so that I can visualize how this would work. once we have a concrete description of one thing, it's easy to think of more cases that are analogous, and thus generalize. But it's hard for me to go the other way. I'm not against this idea (although adding a new feature is a very big ask) I just want to understand what and more important _why_ this is needed. and I need a concrete use case to understand this.

**Comment by jamen** [comment]
@dominictarr I'm not sure what you want me to explain because I thought I covered it all.  I guess I will just try to explain use start to finish:

 1. The user creates different pipelines associated to names, these are "tasks".  They can depend on other tasks by name, and be started via a CLI tool.  So for example, you can make 3 tasks named `html`, `css`, and `js`, and have your `html` depend on `css` and `js` tasks.  This is like how gulp operates, but with node streams instead.
 2. The user uses `pull-vinyl` in these pipelines to read and write files from their project.  For example, you stream in `src/**.sass` files with `vinyl.read`, compile them with a `pull-sass`, and output them with `vinyl.write`.
 3. But, the user should be able to use any streams in the pipelines they want.  For example, streaming to/from FTP with a different `pull-*` module, or streaming buffers instead of vinyl.

The problem here is, in order to make a task system I need to know when `pull(...)` is finished.  If you have a task with a dependency task, it runs the dependency first, and then starts.  So I need a way to measure that without catering to specific sink streams...  But to me, it just feels like a generally needed thing, because I see a lot of sinks have `onEnd` callbacks, I'm just calling for a more standard cooked in way, perhaps built into `pull(...)` or some other way.

If an analogy would help: it's like if Node's `Writable` lacked a `'finish'` event.

**Comment by nichoth** [comment]
@jamen Maybe it would be good to make your desired api changes to pull-stream for your project, so we can see what it would look like. It's hard for me to visualize why your project wouldn't be possible with the existing api, for example using a through stream with an on-end cb.

**Comment by dominictarr** [comment]
okay, looking at your api.

``` js
task(name, [deps...], [pipeline...])
```
deps can be empty, in which case the task will be executing immediately. if there are deps, then it waits for those other pipelines to end before running the next one.

but why does a task specifically need to be a stream? I think a task may work better as a continuable - i.e. a function that takes a single callback.
``` js
task(name, [deps...], function (cb) {
  pull(pipeline..., sink(cb))
})
```
it's a lot more explicit, and it works with any kind of stream, or async thing. would this also work?

**Comment by dominictarr** [comment]
oh, incidentially - the way I was thinking you'd implement this, if we where going to add this to pull-streams, would be to have a sink return a continuable. normally a through returns a source (which is id'd because it takes two args) so if you returned a continuable (one arg) then it is obviously different.

also, if you use `cont.to` this already works without any code changes.

since for incomplete pipelines, the last source is returned, and normally a sink returns nothing.
but if you returned a continuable, `pull()` would just return that.
``` js
pull(
  source, through...,
  function (source) {
    return function (cb) {
      WriteFile(filename, cb)(source)
    }
  }
) (function (err) { //calling th//calling this starts the pipeline flowing!is starts the pipeline flowing!
  //when this function is called, it's complete.
})
```

then, your api becomes

``` js
task(name, [deps..], pull(source..., sinkThatReturnsContinuable))
```
but that would actually be the same code that takes the continuable directly!

however, since having some sinks return a continuable is quite confusing, i'd probably just use it with the continueable directly. Or, you could write sinks that return continuables if you don't pass them a callback directly.

anyway, this already works and

**Comment by jamen** [comment]
Okay, thanks for the input.

You're right about the callback.  I wanted to avoid that way because I thought the array usage was nice and made sense with how `pull(...)` worked.  If I were to use callbacks, I might as well use any other task system (e.g. `gulp` can do something like that already)

Your idea about continuables is interesting.  I like it!

**Comment by ahdinosaur** [comment]
thanks for starting this discussion @jamen. :cat: 

> I know that sink modules usually provide a callback like onEnd, but this is not really consistent

yeah, i've noticed this about `onEnd` as well  i think it'd be great if this was standardized or at least recommended in some consistent way.

> the way I was thinking you'd implement this, if we where going to add this to pull-streams, would be to have a sink return a continuable. normally a through returns a source

ooooh, yeah, i like this idea too.

**Comment by jamen** [comment]
I created PR at #88

**Comment by ahdinosaur** [comment]
talked about this over lunch with @mixmix and @pietgeursen. we noticed that this is a non-breaking change if the existing sinks still immediately call the source and simply return the `onEnd` function. but maybe we'd rather return a continuable that starts the sink and calls the callback when the sink ends, which is a breaking change, and has been documented by @jamen in https://github.com/pull-stream/pull-stream/pull/89. i'm in favor of this change, it means we can pass around completed pipelines similar to partial pipelines, and separately call to start the pipeline.

**Comment by dominictarr** [comment]
This isn't a breaking change to `pull`, but it is a breaking change to `pull.drain` and friends.
Starting the action without waiting for the callback would be a bad continuable, it shouldn't be the default. if you really wanted an eagre continuable, you could make a module for that though...

lets not rush into this. (i.e. changing behavior of all the sinks), given that @jamen's need can just be settled by just using continuables directly. Unless people can come up with other cases that really benefit from passing around continuables.

that said, I'm willing to be persuaded, but I want to see examples, there would be a lot of things to update.

you may find some amunition here https://github.com/dominictarr/pull-cont

while we are here, I'm reminded that we don't have a way to detect when [muxrpc](https://github.com/ssbc/muxrpc) sinks have ended.

also, how does this work in the case of duplex streams?

**Comment by jamen** [comment]
So I've created [pull-drain](https://github.com/jamen/pull-drain) to test this idea out.  I really like it.

One thing though, if the user provides no callback in the continuable (e.g. `pull(...streams)()`) I assume the default behavior should be to throw the error? It would seem annoying for it to swallow them in a `noop` or something.

**Comment by dominictarr** [comment]
yes you should throw the error

**Comment by jamen** [comment]
Closing this since the continuables have been noted.  I dont think we should make the breaking changes to core either, could easily be an alternative `pull-stream-cont` package.
