### ISSUE TITLE
Using `babel-plugin-pipe-operator-curry`

### ISSUE THREAD

**Issue by jamen** [pull-stream/pull-stream#90]
Thought I would bring to light a neat little thing I discovered.

You can use [`babel-plugin-pipe-operator-curry`](https://www.npmjs.com/package/babel-plugin-pipe-operator-curry) to replace `pull`, and get some neat syntax:

```js
count(10)
| map(x => x * 3)
| log()
```

**Comment by dominictarr** [comment]
this is cute, but it doesn't work for duplex streams and you can't do pull(through1, through2) => through12
