### ISSUE TITLE
Transfer ownership of stream

### ISSUE THREAD

**Issue by dryajov** [pull-stream/pull-stream#91]
I have a duplex stream that I want to read from in one place (handshake) and pass the same stream down to something else for further reading/writing. Suppose I don't have access to the original source of the stream (socket), how would I go about doing that? 

@dominictarr @dignifiedquire

**Comment by dominictarr** [comment]
You may be looking for the pull-handshake module.

https://github.com/pull-stream/pull-handshake it allows you to read byte lengths from a stream (probably what you need) and then get return a the rest of the stream as a regular stream (of buffers) again.

**Comment by dryajov** [comment]
@dominictarr pull-handshake worked like a charm, thanks. I'll try to add some examples to make it clearer how it should be used, it got me a while to wrap my head around it.

**Comment by dominictarr** [comment]
@dryajov that would be awesome!
