### ISSUE TITLE
Updating package links

### ISSUE THREAD

**Issue by jamen** [pull-stream/pull-stream#94]
There is lot of `package.json` i see with links that were transferred from profiles.  Sometimes when I find them on npm, the github link will give me 404 instead of redirecting.  I could update them, but I don't want to be noisy with a bunch of PRs so checking here instead.

**Comment by ahdinosaur** [comment]
hey @jamen, that sounds great to me. :+1: 

what do you think @dominictarr?

**Comment by dominictarr** [comment]
@jamen yeah I'll merge it
