### ISSUE TITLE
async vs sync question

### ISSUE THREAD

**Issue by aafrey** [pull-stream/pull-stream#95]
I've been reviewing the pull-stream materials and I'm looking for some clarification if possible. Reading through @dominictarr 's blog post on pull-streams and I can't figure out what makes this `values` example async??
```
function values(array) {
  var i = 0
  return function (abort, cb) {
    if(abort) return cb(abort)
    return cb(i >= array.length ? true : null, array[i++])
  }
}
```
I understand what the function does, but it looks the the callback in the returned function would execute synchronously, not asynchronously? would really appreciate some clarification. Thanks!

**Comment by nichoth** [comment]
pull streams can indeed either be sync or async. This is something to keep in mind when you are using them. You have to know whether the source is sync or async when you use it. This makes pull-stream more versatile since it can be used either way

**Comment by regular** [comment]
@aafrey I think the definition of async here is "takes a callback function". The point here I guess is: while in this example the function indeed produces values in the same tick as the returned function is called, it _could_ be changed to produce the value at any later time, and that would work with _no change to the code that consumes the value!_

**Comment by aafrey** [comment]
@nichoth @regular appreciate the comments! very helpful. so just for some further clarification if at any point, an async pull-stream is incorparated, the entire flow could be turned async? i.e...

 `sync source -> sync through -> async through -> sink`  <--- this flow would "morph" to an async flow?

**Comment by regular** [comment]
Yes. Try this:

```
var pull = require('pull-stream')

console.log('this tick')
setImmediate( ()=> console.log('next tick') )

pull(
  pull.values([1,2,3]),
  pull.map( (x)=> 2*x ),
  pull.log()
)

pull(
  pull.values([10,20,30]),
  pull.asyncMap( (x, cb)=> setImmediate( ()=> cb(null, 2*x)) ),
  pull.log()
)
```

Will output

```
this tick
2
4
6
next tick
20
40
60
```

**Comment by aafrey** [comment]
very cool! thanks again to you both for the clarification!

**Comment by dominictarr** [comment]
yup, good question @aafrey thanks everyone!
